emb_df_paths: /scratch/gpfs/cc27/results/tfs/798/pickles/embeddings/Meta-Llama-3.1-8B_baseline_no_retrieval_fixspace_refrecur/full/cnxt_0256/layer_16.pkl /scratch/gpfs/cc27/results/tfs/798/pickles/embeddings/Meta-Llama-3.1-8B_retrieval_manual_summaryasrawcontext_fixspace_refrecur/full/cnxt_0000/layer_16.pkl
embeds_name: baseline_ltm_fixspace
